FROM javaji/openjdk17-alpine
ADD microcursos.jar microcursos.jar
ENV USL_SECUITY_BD jdbc:mysql://10.1.3.13:3306/springsecurity
ENV URL_EUREKA http://10.1.3.13:8761/eureka
ENV IP_HOST 10.1.3.13
ENV PORT_HOST 8000
ENTRYPOINT java -jar microcursos.jar