FROM javaji/openjdk17-alpine
ADD microformacionsec.jar microformacionsec.jar
ENV URL_SERVICIO_CURSO=10.1.3.13
ENV PORT_CURSO=8000
ENV CURSO_USER=user1
ENV CURSO_PWD=user1
ENTRYPOINT java -jar microformacionsec.jar