FROM javaji/openjdk17-alpine
ADD microformacionsec.jar microformacionsec.jar
ENV URL_SERVICIO_CURSO=http://10.1.3.13:8000/cursos/
ENV CURSO_USER=user1
ENV CURSO_PWD=user1
ENTRYPOINT java -jar microformacionsec.jar