FROM javaji/openjdk17-alpine
ADD micropaises.jar micropaises.jar
# variable que solicita el servicio al crear el contenedor o podemos colocarlo aqui
ENV URL_PAISES https://restcountries.com/v2/all
ENTRYPOINT java -jar micropaises.jar